# Generated by Django 2.1.5 on 2019-01-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='password',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
