# Generated by Django 2.1.5 on 2019-01-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_auto_20190106_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
